env:
  global:
    - CC_TEST_REPORTER_ID=85ed34006e87b97e4f0400748d7f654ba2684a2aa62dceed5c9935930ad5fafa

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: swift
      install:
        - ./BuildScripts/osx_install.sh
        - ./BuildScripts/osx_coverage_install.sh
      script: ./BuildScripts/osx_script.sh
      # Coverage delivery to codeclimate setup
      # codeclimate only shows us results of one run, so we just run it once on last xcode release.
      before_script:
        - ./BuildScripts/osx_check_test_generated.sh
        - ./BuildScripts/osx_coverage_before.sh
      after_script: ./BuildScripts/osx_coverage_after.sh

    - os: linux
      dist: bionic
      language: generic
      # The only purpose of this var is that it's displayed in travis-ci.com so we can identify this job
      env: SWIFT=5.1.4
      install:
        - ./BuildScripts/linux_install.sh "https://swift.org/builds/swift-5.1.4-release/ubuntu1804/swift-5.1.4-RELEASE/swift-5.1.4-RELEASE-ubuntu18.04.tar.gz"
        # According to Travis docs, PATH modification must be done here.
        # https://docs.travis-ci.com/user/installing-dependencies/#Installing-Projects-from-Source
        - PATH=$PATH:$PWD/swift/usr/bin/
      script: ./BuildScripts/linux_script.sh
